name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web/backend

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: web/backend

      - name: Run tests
        run: cargo test --verbose
